const express = require('express');
const router = express.Router();
const { requestNonce, verify } = require('../controllers/authController');
console.log("AUTH ROUTER LOADED");

/**
 * Request Nonce
 * Endpoint to generate a random nonce for a given wallet address.
 * Note: Controller reads body, though this is currently a GET route.
 * 
 * Request Body:
 * {
 *   "wallet_address": "string (Valid Ethereum wallet address)"
 * }
 * 
 * Response:
 * {
 *   "nonce": "string (The nonce prefix + random hex)"
 * }
 */
router.get('/nonce', requestNonce);

router.post('/nonce', (req, res) => {
    res.json({
        message: 'This endpoint expects a get request with a valid wallet addresss'
    });
});

router.get('/verify', (req, res) => {
    res.json({
        message: 'This endpoint expects a post request with a valid wallet address and signature'
    });
});

/**
 * Verify Signature (Login / Register)
 * Verifies the signature for the generated nonce and either logs the user in or registers them.
 * 
 * Request Body:
 * {
 *   "wallet_address": "string (Valid Ethereum wallet address)",
 *   "nonce": "string (The nonce received from the /nonce endpoint)",
 *   "signature": "string (The signature generated by signing the nonce)",
 *   "mode": "string ('LOGIN' or 'REGISTER')",
 *   "role": "string ('CLIENT' or 'STORAGE_PEER')",
 *   
 *   // The following fields are ONLY required if mode="REGISTER" and role="STORAGE_PEER"
 *   "os_type": "string (The operating system of the peer)",
 *   "declared_capacity": 100 // number (Must be a positive number)
 * }
 * 
 * Response:
 * {
 *   "token": "string (JWT Token)"
 * }
 */
router.post('/verify', verify);

module.exports = router;

